version: '2'
services:
  web:
    build: .
    ports:
      - "9000:80"
    volumes:
      - .:/app
      - .:/var/www
  test:
    build: ../tests2
    depends_on:
      - web
    command: curl http://web
networks:
  default:
    driver: bridge
    